### ISSUE TITLE
Derive Clone for update.

### ISSUE THREAD

**Issue by bytebuddha** [little-dude/xrl#1]
Hey cool library!
I am using it to serialize xi types in my own frontend. Is there a reason why Clone isn't derived for Update, Operation, OperationType?

**Comment by little-dude** [comment]
Hi!

I'm glad it's useful! No reason why it's not derived, no. I just didn't need it.
I can make a PR tonight for this, or I'll accept a PR adding these derive.
What frontend are you working on?

**Comment by little-dude** [comment]
Btw I'm a little curious: why do you need to clone the update exactly?
They are pretty frequent and can be quite large, it may be a little expensive to clone them.

**Comment by bytebuddha** [comment]
Cool, I'll make a PR later adding it.

I'm currently working on a frontend using WebReder(Thinking about naming it Zen), but i'm just in the very early stages of it and don't have much to show at the moment. 

I only plan on using Clone in debug mode to work with my event logging system so i'm not to concerned about the performance hit.
